name: Ensure TypeDoc is up-to-date

on:
  pull_request:
    branches:
      - master

jobs:
  typedoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
      - run: npm ci
      - run: npm run build:doc
      - name: Check for changes in the docs
        run: git diff --exit-code docs
